# _config.yml
title: FlashFocus
description: Boost your learning with flashcards — ready-made or custom decks.

# GitHub Pages settings
url: "https://jaletechs.github.io"
baseurl: "/flash-focus-site"

# Enable remote themes
plugins:
  - jekyll-remote-theme

# Point at the Minimalistic theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

# (Optional) Theme customization
color-scheme: auto
favicon: true

# Nav links
navigation:
  - name: Home
    link: /flash-focus-site/
  - name: Privacy
    link: /flash-focus-site/privacy.html
  - name: Support
    link: /flash-focus-site/support.html
