# _config.yml
title: FlashFocus
description: Boost your learning with flashcards — ready-made or custom decks.

# GitHub Pages settings
url: "https://jaletechs.github.io"
baseurl: "/flash-focus-site"

# Enable remote themes
plugins:
  - jekyll-remote-theme

# Point at the Minimalistic theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

# (Optional) Theme customization
color-scheme: auto
favicon: true
logo: /assets/img/logo.png

# Nav links
navigation:
  - name: Home
    link: /flash-focus-site/
  - name: Privacy
    link: /flash-focus-site/privacy.html
  - name: Support
    link: /flash-focus-site/support.html

platforms:
  - name: Instagram
    icon: '<i class="fa-brands fa-instagram"></i>'
    link: https://instagram.com/minervaeduapp
  - name: Threads
    icon: '<i class="fa-brands fa-threads"></i>'   # or use an <img> if you placed an SVG
    link: https://www.threads.net/@minervaeduapp
  - name: X
    icon: '<i class="fa-brands fa-x"></i>'         # or 'fa-twitter'
    link: https://x.com/minervaeduapp
